### ISSUE TITLE
[Bug] - 'RZ_BIN_STRING_ENC_WIDE32_BE' was not declared in this scope; did you mean 'RZ_STRING_ENC_UTF32BE'

### ISSUE THREAD

**Issue by re-fox** [radareorg/r2ghidra-dec#290]
Building from `rizin/master` and `rz-ghidra/master` on `fedora:latest`

Maybe caused by https://github.com/rizinorg/rizin/pull/2716

```
/rz-ghidra/src/RizinScope.cpp:470:38: error: 'RZ_BIN_STRING_ENC_WIDE32_BE' was not declared in this scope; did you mean 'RZ_STRING_ENC_UTF32BE'?
  470 |                                 case RZ_BIN_STRING_ENC_WIDE32_BE:
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      RZ_STRING_ENC_UTF32BE
make[2]: *** [CMakeFiles/core_ghidra.dir/build.make:118: CMakeFiles/core_ghidra.dir/src/RizinScope.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs...
```
