### ISSUE TITLE
use git tags to better indicate compatibility to radare2 version

### ISSUE THREAD

**Issue by anthraxx** [radareorg/r2ghidra-dec#92]
Hi,

It would be awesome if this repo could use some git tags / releases to indicate compatibility to certain radare2 versions. For example the latest HEAD is not compatible with the latest release 4.3.1 of radare2, however going back to 1ff56278440bfcf7a1f481aeb91feb6a8dc51613 before the typedef support was added is compatible.
Some kind of mechanism would be nice and maybe it would be as simple as cutting a r2ghidra-dec whenever radare2 cuts a release?

**Comment by radare** [comment]
agree

**Comment by thestr4ng3r** [comment]
Hmm yeah, maybe tagging the newest commit before breaking compatibility with a certain r2 version could work. Later, r2pm could detect those.

**Comment by Nicceboy** [comment]
I haven't been able to install ghidra plugin to any radare2 release, tested from 4.2.0 and up, every build failing to:
```sh
/home/nicce/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2Scope.cpp:590:6: error: ‘r_anal_get_function_byname’ was not declared in this scope; did you mean ‘r_anal_get_function_at’?
  590 |  if (r_anal_get_function_byname(core->anal, name.c_str()))
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |      r_anal_get_function_at
/home/nicce/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2TypeFactory.cpp: In member function ‘Datatype* R2TypeFactory::queryR2(const string&, std::set<std::__cxx11::basic_string<char> >&)’:
/home/nicce/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2TypeFactory.cpp:157:8: error: ‘R_TYPE_TYPEDEF’ was not declared in this scope
  157 |   case R_TYPE_TYPEDEF:
```

I guess it is related to this and might work with radare2 master?

**Comment by thestr4ng3r** [comment]
Correct, r2ghidra-dec master will always follow r2 master.

**Comment by anthraxx** [comment]
@Nicceboy you basically discovered the very purpose of this while issue :cat: you will always need to find the matching commit right now, hence i suggested to tag in sync to radare2. Like you will see that 1ff5627 works fine with 4.3.1, for now you will need to find the appropriate commit yourself.

**Comment by Nicceboy** [comment]
Hmm, I think r2pm is not providing possibility to use specific commit, so I need to do it manually as well. I have no idea how other plugins are dependent of version of radare2, in case tag support etc. would be beneficial for package manager as well.

**Comment by thestr4ng3r** [comment]
r2ghidra will release in sync with r2 from now on, first release for 4.4: https://github.com/radareorg/r2ghidra-dec/releases/tag/v4.4.0
Newer commits may work with the release but only the tag is guaranteed.
r2ghidra master will be in sync with r2 master.

**Comment by anthraxx** [comment]
Thanks a lot, much appreciated.

**Comment by bazuchan** [comment]
r2pm does `git clone --depth 1` and have no tags cloned.
